GET http://localhost:3000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicHJ1ZGh2aSIsImlhdCI6MTcwMTE4NTM1MywiZXhwIjoxNzAxMTg4OTUzfQ.QEQ6HC4fmFyRWVEJlIVBNXLzyEVRY9nhG2Dp2NlcH7Y